version: 1
build:
  binary: planqd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000uatom
  - 100000000000000000000aplanq
- name: bob
  coins:
  - 5000000000000aplanq
- name: faucet
  coins:
  - 1000000000000000000000000000aplanq

client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: aplanq
    evm:
      params:
        evm_denom: aplanq
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: aplanq
    mint:
      params:
        mint_denom: aplanq
    staking:
      params:
        bond_denom: aplanq
  chain_id: planq_7000-1
validators:
- name: alice
  bonded: 100000000000000000000aplanq
  app:
    api:
      enable: true
    json-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
  home: $HOME/.planqd
